mysite/members/urls.py
from django.urls import path 
from . import views

app_name = 'members'
urlpatterns = [
    path('', views.main, name='main'),
    path('members/', views.members, name='members'),
    path('members/details/<slug:slug>', views.details, name='details'),
    path('testing/', views.testing, name='testing'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
]

mysite/members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    phone = models.IntegerField(null=True)
    joined_date = models.DateField(null=True)
    slug = models.SlugField(default="", null=False)
    
    def __str__(self):
        return f"{self.firstname} {self.lastname}"
    

mysite/members/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Member

# Create your views here.
def members(request):
    mymembers = Member.objects.all().values()
    firstnames = Member.objects.values_list('firstname')
    return render(request, 'all_members.html', {'mymembers': mymembers, 'firstnames': firstnames})


def details(request, slug):
    mymember = get_object_or_404(Member, slug=slug)
    return render(request, 'details.html', {'mymember': mymember})

def main(request):
    return render(request, 'main.html')

def testing(request):
    mymembers = Member.objects.all().values()
    fruits=["Banana", "Orange", "Lemon", "Papaya"]
    return render(request, 'template.html', {'mymembers': mymembers, 'fruits': fruits})

mysite/members/templates/all_members.html
{% extends 'master.html' %}

{% block title %}
    My Tennis Club - List of all members
{% endblock title %}

{% block content %}
    <div class="mycard">
        <h2>Members</h2>
        <ul>
            {% for x in mymembers %}
                <li onclick="window.location = '{% url 'members:details' x.slug %}' ">
                    {{ x.firstname }} {{ x.lastname }}
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

mysite/members/templates/details.html
{% extends 'master.html' %}

{% block title %}
    Details about {{ mymember.firstname }} {{ mymember.lastname }}
{% endblock title %}

{% block content %}
    <div class="myc">
        <h1>{{ mymember.firstname }} {{ mymember.lastname }}</h1>
        <p>Phone: {{ mymember.phone }}</p>
        <p>Member since: {{ mymember.joined_date }}</p>
    </div>

    <p>Back to <a href="{% url 'members:members' %}">Members</a></p>
{% endblock content %}

mysite/members/templates/footer.html
<footer>
    <p>You have reached the bottom of this page, thank you for your time. </p>
</footer>

mysite/members/templates/main.html
{% extends 'master.html' %}

{% block title %}
    My Tennis Club
{% endblock title %}

{% block content %}
    <div class="main">
        <h1>My Tennis Club</h1>

        <h3>Members</h3>
        
        <p>Check out all our <a href="{% url 'members:members' %}">members</a></p>
    </div>

{% endblock content %}

mysite/members/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% load bootstrap5 %}
    {% bootstrap5_css %}
    {% bootstrap_javascript %}
</head>
<body>
    
    <div class="container">
        <ul class="nav bg-info">
            <li class="nav-item">
                <a href="{% url 'members:main' %}" class="nav-link link-light"></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'members:members' %}" class="nav-link link-light"></a>
            </li>
        </ul>
    </div>

    {% block content %}{% endblock content %}
</body>
</html>

mysite/members/templates/myfirst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First HTML</title>
</head>
<body>
    <h1>Hello World!</h1>
    <p>Welcome to my first Django project!</p>
</body>
</html>

mysite/members/templates/mymenu.html
<div>
    HOME | {{ me }} | ABOUT | FORUM | {{ sponsor }}
</div>

mysite/members/templates/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template</title>
    <link rel="stylesheet" href="{% static 'myglobal.css' %}">
</head>
<body>
    {% include 'mymenu.html' with me='TOBIAS' sponsor='W3SCHOOLS' %}

    <ul>
        {% for x in mymembers %}
            <li>{{ x.firstname }}</li>
        {% endfor %}
    </ul>

    {% with greeting=1 %}
        {% if greeting %}
            <h1>Hello</h1>
        {% else %}
            <h1>Bye</h1>
        {% endif %}
    {% endwith %}

    <ul>
        {% for x in fruits %}
            <li style='color: {% cycle 'blue' 'pink' %}'>
                {{ x }}
            </li>
        {% endfor %}
    </ul>
    
    <ul>
        {% for x in fruits %}
            <li
                {% if forloop.first %}
                    style='background-color:lightblue;'
                {% endif %}
                
                {% if forloop.last %}
                    style='background-color:lightyellow;'
                {% endif %}
            >
                {{ x }}
            </li>
        {% endfor %}
    </ul>

    <ul>
        {% for x in fruits %}
            <li>{{ forloop.revcounter1 }}</li>
        {% endfor %}
    </ul>

    {% lorem 2 b random %}
    <br>
    <small>{% now "Y-m-d G:i:s" %}</small>

    {% include 'footer.html' %}
</body>
</html>